// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhoneNumberAnalyzer.Data;

#nullable disable

namespace PhoneNumberAnalyzer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803083756_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Length")
                        .HasMaxLength(9)
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("PatternRules");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternRuleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatternTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PatternTemplateId");

                    b.ToTable("PatternRuleGroups");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternRulePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PatternRuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasAnnotation("Range", new[] { 0, 9 });

                    b.HasKey("Id");

                    b.HasIndex("PatternRuleId");

                    b.ToTable("PatternRulePositions");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternRuleValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatternRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatternRuleId");

                    b.ToTable("PatternRuleValues");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("PatternTemplates");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.UserAuthProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAuthProviders");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternRule", b =>
                {
                    b.HasOne("PhoneNumberAnalyzer.Data.Entities.PatternRuleGroup", "Group")
                        .WithMany("Rules")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternRuleGroup", b =>
                {
                    b.HasOne("PhoneNumberAnalyzer.Data.Entities.PatternRuleGroup", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PhoneNumberAnalyzer.Data.Entities.PatternTemplate", "PatternTemplate")
                        .WithMany("RuleGroups")
                        .HasForeignKey("PatternTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentGroup");

                    b.Navigation("PatternTemplate");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternRulePosition", b =>
                {
                    b.HasOne("PhoneNumberAnalyzer.Data.Entities.PatternRule", "PatternRule")
                        .WithMany("Positions")
                        .HasForeignKey("PatternRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatternRule");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternRuleValue", b =>
                {
                    b.HasOne("PhoneNumberAnalyzer.Data.Entities.PatternRule", "PatternRule")
                        .WithMany("Values")
                        .HasForeignKey("PatternRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatternRule");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternTemplate", b =>
                {
                    b.HasOne("PhoneNumberAnalyzer.Data.Entities.User", "Owner")
                        .WithMany("PatternTemplates")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.UserAuthProvider", b =>
                {
                    b.HasOne("PhoneNumberAnalyzer.Data.Entities.User", "User")
                        .WithMany("AuthProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternRule", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternRuleGroup", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.PatternTemplate", b =>
                {
                    b.Navigation("RuleGroups");
                });

            modelBuilder.Entity("PhoneNumberAnalyzer.Data.Entities.User", b =>
                {
                    b.Navigation("AuthProviders");

                    b.Navigation("PatternTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
